"""Repeated runs: across seeds, and across the parameters the result might depend on.

Every metric this project reports is a property of two things - the model, and the one
synthetic dataset it happened to be trained on. A single run cannot tell those apart. Change
the seed and the population, the campaign structure, the mule rings and the test window all
change together, so a headline recall from one seed is a sample of size one from a
distribution nobody has looked at.

That matters more here than in ordinary ML work, because the dataset is *generated by the same
authors as the defence*. The honest way to report it is mean and spread across seeds, and to
show what happens when the knobs that set the difficulty are moved. Three sweeps are worth
running:

* **Seeds.** Same configuration, different worlds. The spread is the error bar that belongs
  on every number in the write-up.
* **Prevalence.** Real portfolios differ by more than an order of magnitude in fraud rate, and
  precision at a fixed budget moves with prevalence by construction. A result quoted at one
  rate says little about a bank at another.
* **Difficulty knobs** - how loudly attacks signal, how many false-positive traps the benign
  traffic contains, how much of the fraud is evasion-tuned. If recall collapses when one of
  these moves slightly, the headline was an artefact of that setting rather than a finding.

Each configuration is a full generate-and-train cycle, so these are minutes each and the
defaults stay small. Deep studies - leave-one-vector-out, permutation importance, the
ablation grid - are skipped, because the comparison here is between runs rather than within
one.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Sequence

import numpy as np
import pandas as pd

from .config import Config
from .defend.pipeline import run_defence
from .defend.stats import summarise_seeds
from .generate.campaign import generate_dataset
from .generate.fidelity import assess
from .identify.library import load_library

# Metrics carried out of each run. Deliberately short: a wide table across many runs is
# unreadable, and these are the numbers the submission is judged on.
TRACKED = ("recall", "precision", "f1", "value_recall", "pr_auc", "partial_auc_2pct",
           "roc_auc", "false_positive_rate", "alerts_per_10k", "fraud_rate")


@dataclass
class SweepResult:
    """Per-run rows plus the across-run summary."""

    runs: pd.DataFrame = field(default_factory=pd.DataFrame)
    summary: pd.DataFrame = field(default_factory=pd.DataFrame)
    label: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "label": self.label,
            "runs": self.runs.to_dict("records"),
            "summary": self.summary.to_dict("records"),
        }


def _one_run(cfg: Config, library, *, verbose: bool = False) -> Dict[str, float]:
    """Generate a dataset and train on it, returning just the tracked metrics."""
    result = generate_dataset(cfg, library)
    fidelity = assess(result.transactions)
    artifacts = run_defence(result.transactions, result.corpus, cfg, verbose=verbose,
                            with_zero_day=False, with_importance=False)
    head = artifacts.headline.to_dict()

    row = {k: head[k] for k in TRACKED if k in head}
    row["rows"] = head["rows"]
    row["fraud"] = head["fraud"]
    row["fidelity"] = fidelity.overall
    row["fidelity_flags"] = len(fidelity.flags)
    # The separability probes are the reason for the whole exercise, so they travel with the
    # metrics rather than being reported in a separate place that can drift out of step.
    for key in ("joint_separability", "derived_separability"):
        detail = fidelity.details.get(key) or {}
        if "recall_at_review_budget" in detail:
            row[f"{key}_recall"] = detail["recall_at_review_budget"]
    return row


def across_seeds(cfg: Config, seeds: Sequence[int], *, verbose: bool = True) -> SweepResult:
    """The same configuration in several independently generated worlds.

    This is the single largest credibility upgrade available for the compute: it converts every
    headline number from an assertion into an estimate with a spread. A recall of 68% that
    moves by two points across five seeds means something quite different from one that moves
    by fifteen.
    """
    library = load_library()
    rows = []
    for i, seed in enumerate(seeds, start=1):
        if verbose:
            print(f"  seed {seed} ({i}/{len(seeds)})")
        trial = copy.deepcopy(cfg)
        trial.seed = int(seed)
        row = _one_run(trial, library)
        rows.append({"seed": int(seed), **row})

    runs = pd.DataFrame(rows)
    summary = summarise_seeds([{k: v for k, v in r.items() if k != "seed"} for r in rows])
    return SweepResult(runs=runs, summary=summary, label=f"{len(seeds)} seeds")


# Knobs worth sweeping, and where each lives in the config tree. Kept as an explicit map
# rather than resolved by dotted-path lookup so that a typo on the command line is rejected
# with a list of valid names instead of quietly setting an attribute nobody reads.
KNOBS: Dict[str, Callable[[Config, float], None]] = {
    "target_fraud_rate": lambda c, v: setattr(c.attacks, "target_fraud_rate", float(v)),
    "signal_emission": lambda c, v: setattr(c.attacks, "signal_emission", float(v)),
    "evasion_share": lambda c, v: setattr(c.attacks, "evasion_share", float(v)),
    "hard_negative_rate": lambda c, v: setattr(c.benign, "hard_negative_rate", float(v)),
    "n_days": lambda c, v: setattr(c.benign, "n_days", int(v)),
    "n_customers": lambda c, v: setattr(c.population, "n_customers", int(v)),
}


def sensitivity(cfg: Config, knob: str, values: Sequence[float], *,
                seeds: Optional[Sequence[int]] = None,
                verbose: bool = True) -> SweepResult:
    """Sweep one parameter and report the metrics as a curve.

    A caveat measured is worth more than a caveat written. The README used to concede that
    recall varies with dataset size and with how loudly attacks signal; a sweep replaces that
    admission with a curve a reader can judge for themselves - and, more usefully, shows
    whether the headline sits on a plateau or on a cliff edge.
    """
    if knob not in KNOBS:
        raise ValueError(f"unknown sweep parameter '{knob}'. "
                         f"Choose one of: {', '.join(sorted(KNOBS))}")
    library = load_library()
    seeds = list(seeds or [cfg.seed])

    rows = []
    for value in values:
        for seed in seeds:
            if verbose:
                print(f"  {knob}={value} seed={seed}")
            trial = copy.deepcopy(cfg)
            trial.seed = int(seed)
            KNOBS[knob](trial, value)
            rows.append({knob: value, "seed": int(seed), **_one_run(trial, library)})

    runs = pd.DataFrame(rows)
    # Average over seeds at each setting, so the curve shows the trend rather than the noise.
    numeric = [c for c in runs.columns if c not in (knob, "seed")]
    summary = runs.groupby(knob, sort=True)[numeric].agg(["mean", "std"]).round(5)
    summary.columns = [f"{a}_{b}" for a, b in summary.columns]
    return SweepResult(runs=runs, summary=summary.reset_index(),
                       label=f"{knob} over {list(values)}")


def paired_seed_comparison(a: SweepResult, b: SweepResult, metric: str = "recall") -> pd.DataFrame:
    """Compare two sweeps seed by seed rather than in aggregate.

    Used when the question is "did this change help", not "what is the level". Pairing on seed
    removes the between-world variance, which is the dominant term here and can easily be
    larger than the effect being tested - so an unpaired comparison of two five-run means will
    usually conclude nothing happened.
    """
    if a.runs.empty or b.runs.empty or "seed" not in a.runs or "seed" not in b.runs:
        return pd.DataFrame()
    left = a.runs.set_index("seed")[metric]
    right = b.runs.set_index("seed")[metric]
    shared = left.index.intersection(right.index)
    if len(shared) == 0:
        return pd.DataFrame()

    diff = (right.loc[shared] - left.loc[shared]).astype(float)
    n = len(diff)
    sd = float(diff.std(ddof=1)) if n > 1 else float("nan")
    stderr = sd / np.sqrt(n) if n > 1 and sd == sd else float("nan")
    return pd.DataFrame([{
        "metric": metric,
        "seeds": n,
        "mean_before": round(float(left.loc[shared].mean()), 5),
        "mean_after": round(float(right.loc[shared].mean()), 5),
        "mean_difference": round(float(diff.mean()), 5),
        "sd_of_difference": round(sd, 5) if sd == sd else np.nan,
        # A t-like ratio rather than a p-value: with five seeds a formal test has almost no
        # power, and reporting the effect against its own noise is the honest summary.
        "difference_over_stderr": round(float(diff.mean() / stderr), 2)
        if stderr and stderr == stderr else np.nan,
    }])
