"""Bake a run's API responses into static JSON, so the console works with nothing running.

The console has to survive a conference hall: no backend, no wi-fi, a laptop that is not the
one it was built on. That means every read has to have an offline answer.

The property that makes this trustworthy rather than a set of fixtures is that **the payload
is generated by calling the same endpoints it replaces**. Nothing here constructs a number,
reshapes a table, or fills a gap. It starts the FastAPI application in-process, issues the
requests the browser would issue, and writes the responses to disk under the paths the client
looks for. If a figure in Demo Mode is wrong, the live API is wrong in exactly the same way -
which is the only kind of wrong worth having, because it is findable.

Two things are sampled rather than copied whole, and both are declared in the manifest:

* The scored test window is ~74,000 rows and would be a 20MB download. A stratified slice is
  taken instead - every decision class and every simulated vector kept - and the client says
  so where a filter cannot be honoured.
* Transaction detail is one file per payment, so only the payments in the slice get one.

Usage::

    python scripts/build_demo_payload.py --run default_run
"""

from __future__ import annotations

import argparse
import json
import math
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

#: Rows kept in the streamable slice. Enough that the stream runs for minutes without
#: repeating and the table has something to scroll, small enough to stay a fast download.
SLICE_ROWS = 4000

#: Payments that get a detail file. The inspector is opened a handful of times in a demo and
#: once or twice by a curious judge; one file per row in the slice would be 4,000 files.
DETAIL_ROWS = 400


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", default="default_run", help="run id under artifacts/")
    parser.add_argument("--out", default="frontend/public/demo",
                        help="where to write the payload")
    parser.add_argument("--slice-rows", type=int, default=SLICE_ROWS)
    parser.add_argument("--detail-rows", type=int, default=DETAIL_ROWS)
    args = parser.parse_args()

    try:
        from fastapi.testclient import TestClient
    except ImportError:
        print("fastapi and httpx are needed to bake the payload: pip install -e '.[serve]'",
              file=sys.stderr)
        return 1

    from redteam.serve.api import create_app

    run = args.run
    out = ROOT / args.out
    if out.exists():
        # A stale file from a previous run's payload would be served forever - the client
        # asks for a path, not for a version - so the directory is rebuilt rather than
        # merged into.
        shutil.rmtree(out)
    (out / run).mkdir(parents=True, exist_ok=True)

    # `raise_server_exceptions=False` so a broken endpoint bakes as an error response the UI
    # can render rather than aborting the whole build. One dead panel beats no payload.
    client = TestClient(create_app(), raise_server_exceptions=False)

    written: List[str] = []

    def bake(path: str, name: str) -> Any:
        response = client.get(path)
        if response.status_code != 200:
            print(f"  ! {path} -> {response.status_code}, skipped")
            return None
        payload = response.json()
        target = out / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(json.dumps(payload, separators=(",", ":")), encoding="utf-8")
        written.append(name)
        print(f"  {name:<34} {_size(target)}")
        return payload

    print(f"baking {run} into {out.relative_to(ROOT)}")

    runs = bake("/api/runs", "runs.json")
    if runs is None:
        print(f"no runs available; is artifacts/{run}/ populated?", file=sys.stderr)
        return 1
    if not any(r.get("run") == run for r in runs):
        print(f"run '{run}' is not in artifacts/. Available: "
              f"{[r.get('run') for r in runs]}", file=sys.stderr)
        return 1

    for endpoint in ("summary", "identify", "fidelity", "defend", "loop", "report"):
        bake(f"/api/runs/{run}/{endpoint}", f"{run}/{endpoint}.json")

    # -- the streamable slice ------------------------------------------------
    print("  sampling the scored test window")
    slice_payload = _slice(client, run, args.slice_rows)
    (out / run / "transactions.json").write_text(
        json.dumps(slice_payload, separators=(",", ":")), encoding="utf-8")
    written.append(f"{run}/transactions.json")
    print(f"  {run + '/transactions.json':<34} "
          f"{_size(out / run / 'transactions.json')} "
          f"({len(slice_payload['rows'])} of {slice_payload['total']} rows)")

    # -- one file per inspectable payment ------------------------------------
    ids = [r["txn_id"] for r in slice_payload["rows"][: args.detail_rows]]
    detail_dir = out / run / "txn"
    detail_dir.mkdir(parents=True, exist_ok=True)
    baked = 0
    for txn_id in ids:
        response = client.get(f"/api/runs/{run}/transactions/{txn_id}")
        if response.status_code != 200:
            continue
        (detail_dir / f"{txn_id}.json").write_text(
            json.dumps(response.json(), separators=(",", ":")), encoding="utf-8")
        baked += 1
    print(f"  {run + '/txn/*.json':<34} {baked} payments")

    manifest = {
        "run": run,
        "baked_from": "the same /api endpoints the live console reads",
        "endpoints": written,
        "transactions": {
            "rows": len(slice_payload["rows"]),
            "of_total": slice_payload["total"],
            "sampling": "stratified: every decision class and every simulated vector kept",
        },
        "transaction_detail": {"payments": baked},
        "note": (
            "Nothing in this payload was written by hand. Every value is a response the live "
            "API produced for this run. Filters the client cannot apply to a sample are "
            "disabled in the interface rather than silently ignored."
        ),
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"\ndone: {_total(out)} across {len(written) + baked + 1} files")
    return 0


def _slice(client, run: str, limit: int) -> Dict[str, Any]:
    """A stratified sample of the scored window, large enough to stream and to scroll.

    Taking the first N rows would be simpler and would produce a slice that is chronological,
    overwhelmingly legitimate, and missing most vectors - so the stream would show almost no
    alerts and the vector filter would come up empty. Sampling by decision class and by vector
    keeps the slice representative of what the run found, at the cost of no longer being a
    time series, which nothing in the interface depends on.
    """
    import pandas as pd

    path = ROOT / "artifacts" / run / "defend_scored_test_set.csv"
    frame = pd.read_csv(path)

    strata = []
    # Every fraudulent payment worth keeping, since they are rare and they are the interesting
    # ones. Then a proportional sample of the legitimate majority to carry the base rate.
    fraud = frame[frame["is_fraud"] == 1]
    alerts = frame[(frame["is_fraud"] == 0) & (frame["decision"] == 1)]
    legit = frame[(frame["is_fraud"] == 0) & (frame["decision"] == 0)]

    strata.append(fraud.head(min(len(fraud), limit // 3)))
    strata.append(alerts.head(min(len(alerts), limit // 6)))
    remaining = max(limit - sum(len(s) for s in strata), 0)
    if remaining and len(legit):
        strata.append(legit.sample(min(remaining, len(legit)), random_state=7))

    sample = pd.concat(strata)
    # Back into time order so the stream reads as a stream rather than as a shuffle.
    if "timestamp" in sample.columns:
        sample = sample.sort_values("timestamp")

    response = client.get(f"/api/runs/{run}/transactions?limit=1")
    envelope = response.json() if response.status_code == 200 else {}

    return {
        "provenance": envelope.get("provenance", {}),
        "source": "defend_scored_test_set.csv",
        "available": True,
        "rows": _records(sample),
        "total": int(len(frame)),
        "cursor": 0,
        "next_cursor": None,
        "sampled": True,
    }


def _records(frame) -> List[Dict[str, Any]]:
    """JSON-safe records: NaN and Infinity are not valid JSON and break JSON.parse."""
    out = []
    for row in frame.to_dict(orient="records"):
        clean = {}
        for key, value in row.items():
            if isinstance(value, float) and not math.isfinite(value):
                clean[key] = None
            elif hasattr(value, "item"):
                clean[key] = value.item()
            else:
                clean[key] = value
        out.append(clean)
    return out


def _size(path: Path) -> str:
    kb = path.stat().st_size / 1024
    return f"{kb / 1024:.1f} MB" if kb > 1024 else f"{kb:.0f} KB"


def _total(root: Path) -> str:
    total = sum(p.stat().st_size for p in root.rglob("*") if p.is_file())
    return f"{total / 1024 / 1024:.1f} MB"


if __name__ == "__main__":
    raise SystemExit(main())
